//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class faculty
    {
        public int fid { get; set; }
        public string fname { get; set; }
        public string femail { get; set; }
        public string fpass { get; set; }
        public string fdept { get; set; }
    }
}
