//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int stuid { get; set; }
        public string sfname { get; set; }
        public string slname { get; set; }
        public string semail { get; set; }
        public string smno { get; set; }
        public string sdept { get; set; }
        public Nullable<int> fid { get; set; }
        public string spass { get; set; }
    }
}
